from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from app.followup_engine import FollowupEngine
from app.followup_queue_bridge import FollowupQueueBridge


def main() -> None:
    decisions = FollowupEngine().run_active()

    # Preserve follow-up numbering generated by the engine's memory state when available.
    # The bridge never sends messages; it only creates approval work items.
    bridge = FollowupQueueBridge()
    added = bridge.apply_many(decisions)

    report = {
        "run_at": datetime.now().isoformat(timespec="seconds"),
        "decision_count": len(decisions),
        "approval_items_added": len(added),
        "decisions": decisions,
        "added_items": added,
    }

    out = Path("data/latest_gmail_followup_bridge.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
